name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Checks
        run: bun run check

      - name: Build
        run: bun run build

      - uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: dist/
          compression-level: 9
